//! Cargo.lock file parser.
//!
//! Parses the TOML-based Cargo.lock format (v3 and earlier) to extract
//! dependency names, versions, and sources.

use serde::Deserialize;
use std::fmt;

/// A dependency extracted from Cargo.lock.
#[derive(Debug, Clone, Deserialize)]
pub struct Dependency {
    pub name: String,
    pub version: String,
    pub source: Option<String>,
}

impl fmt::Display for Dependency {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} v{}", self.name, self.version)
    }
}

/// Represents the top-level structure of a Cargo.lock file.
#[derive(Debug, Deserialize)]
struct CargoLock {
    #[serde(default)]
    package: Vec<LockPackage>,
}

/// A single package entry in Cargo.lock.
#[derive(Debug, Deserialize)]
struct LockPackage {
    name: String,
    version: String,
    source: Option<String>,
}

/// Parse a Cargo.lock file's content and return a list of dependencies.
///
/// Supports both v3 (version field at top) and earlier Cargo.lock formats.
/// Path and git dependencies will have `source` set to their respective URLs,
/// while registry dependencies will have a registry source URL.
///
/// # Errors
///
/// Returns an error if the content is not valid TOML or doesn't match
/// the expected Cargo.lock structure.
pub fn parse_lockfile(content: &str) -> Result<Vec<Dependency>, String> {
    let lock: CargoLock =
        toml::from_str(content).map_err(|e| format!("Failed to parse Cargo.lock: {}", e))?;

    let dependencies: Vec<Dependency> = lock
        .package
        .into_iter()
        .map(|p| Dependency {
            name: p.name,
            version: p.version,
            source: p.source,
        })
        .collect();

    Ok(dependencies)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_simple_lockfile() {
        let content = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my-project"
version = "0.1.0"

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "clap"
version = "4.4.11"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;

        let deps = parse_lockfile(content).unwrap();
        assert_eq!(deps.len(), 3);

        // First package is the root (no source)
        assert_eq!(deps[0].name, "my-project");
        assert_eq!(deps[0].version, "0.1.0");
        assert!(deps[0].source.is_none());

        // Registry dependencies have source
        assert_eq!(deps[1].name, "serde");
        assert_eq!(deps[1].version, "1.0.193");
        assert!(deps[1].source.is_some());

        assert_eq!(deps[2].name, "clap");
        assert_eq!(deps[2].version, "4.4.11");
        assert!(deps[2].source.is_some());
    }

    #[test]
    fn test_parse_empty_lockfile() {
        let content = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3
"#;
        let deps = parse_lockfile(content).unwrap();
        assert!(deps.is_empty());
    }

    #[test]
    fn test_parse_lockfile_with_git_source() {
        let content = r#"
version = 3

[[package]]
name = "some-crate"
version = "0.1.0"
source = "git+https://github.com/user/repo#abc123"
"#;
        let deps = parse_lockfile(content).unwrap();
        assert_eq!(deps.len(), 1);
        assert_eq!(deps[0].name, "some-crate");
        assert!(deps[0].source.as_ref().unwrap().starts_with("git+"));
    }

    #[test]
    fn test_parse_invalid_toml() {
        let content = "this is not valid toml {{{{";
        let result = parse_lockfile(content);
        assert!(result.is_err());
    }

    #[test]
    fn test_dependency_display() {
        let dep = Dependency {
            name: "serde".to_string(),
            version: "1.0.193".to_string(),
            source: Some("registry+https://github.com/rust-lang/crates.io-index".to_string()),
        };
        assert_eq!(format!("{}", dep), "serde v1.0.193");
    }

    #[test]
    fn test_parse_v1_lockfile_without_version() {
        let content = r#"
[[package]]
name = "old-crate"
version = "0.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#;
        let deps = parse_lockfile(content).unwrap();
        assert_eq!(deps.len(), 1);
        assert_eq!(deps[0].name, "old-crate");
    }
}
